- name: Download and install spotifyd
  hosts: local
  tasks:

  - name: Get the latest release version of spotifyd
    uri:
      url: https://api.github.com/repos/Spotifyd/spotifyd/releases/latest
    register: latest_release

  - name: Download the latest ARMv6 binary to /usr/bin/
    unarchive:
      src: "https://github.com/Spotifyd/spotifyd/releases/download/{{ latest_release.json.tag_name }}/spotifyd-linux-armv6-slim.tar.gz"
      dest: /usr/bin
      remote_src: true
    become: true

- name: Configure spotifyd
  hosts: local
  tasks:

  - name: Ensure spotifyd config folder exists
    file: 
      path: ~/.config/spotifyd
      state: directory

  - name: Create config from template
    template:
      src: spotifyd.conf.j2
      dest: ~/.config/spotifyd/spotify.conf

