- name: Download and install Spotifyd
  hosts: local
  tasks:

  - name: Get version tag of latest available Spotifyd release
    block:

      - name: Poll GitHub for latest Spotifyd release
        uri:
          url: https://api.github.com/repos/Spotifyd/spotifyd/releases/latest
        register: latest_spotifyd_release

      - name: Display latest release of Spotifyd discovered
        debug:
          msg: "Found latest release of Spotifyd as: {{ latest_spotifyd_release.json.tag_name }}"

      - name: Set latest version of Spotifyd discovered as version to install
        set_fact:
          spotifyd_version: "{{ latest_spotifyd_release.json.tag_name }}"

    when: spotifyd_version == "latest"

  - name: Show Spotifyd version to install
    debug:
      msg: "Installing Spotifyd version: {{ spotifyd_version }}"

  - name: Download the desired Spotifyd ARMv6 binary to /usr/bin/
    unarchive:
      src: "https://github.com/Spotifyd/spotifyd/releases/download/{{ spotifyd_version }}/spotifyd-linux-armv6-slim.tar.gz"
      dest: /usr/bin
      remote_src: true
    become: true

- name: Configure spotifyd
  hosts: local
  tasks:

  - name: Ensure spotifyd config folder exists
    file:
      path: ~/.config/spotifyd
      state: directory

  - name: Create config from template
    template:
      src: spotifyd.conf.j2
      dest: ~/.config/spotifyd/spotify.conf

- name: Set up spotifyd as systemd service
  hosts: local
  tasks:

  - name: Create systemd service file
    copy:
      src: spotifyd.service
      dest: /etc/systemd/user/spotifyd.service
    become: true

  - name: Start spotifyd daemon
    systemd:
      name: spotifyd
      daemon_reload: true
      state: started
      enabled: true
      scope: user
